var students = [{name: 'fooz'}, {name: 'abdlrrahman'}, {name: 'abdo'}, {name: 'adem'}, 
								{name: 'adnen'}, {name: 'ahmed'}, {name: 'ali'}, {name: 'amera'}, 
								{name: 'aouini'}, {name: 'anas'}, {name: 'bilel'}, {name: 'dhia'}, 
								{name: 'essam'}, {name: 'fares'}, {name: 'fatima'}, {name: 'firas'}, 
								{name: 'khoubaieb'}, {name: 'farouk'}, {name: 'fooz'}, {name: 'hmam'}, 
								{name: 'hamza'}, {name: 'hania'}, {name: 'hashem'}, {name: 'heni'}, 
			   				{name: 'houda'}, {name: 'insaf'}, {name: 'jhhed'}, {name: 'lina'}, 
			   				{name: 'maher'}, {name: 'malik'}, {name: 'mehdi'}, {name: 'slaimia'},
								{name: 'belkheir'}, {name: 'weslati'}, {name: 'fared'}, {name: 'sbeta'}, 
								{name: 'muftah'}, {name: 'nejah'}, {name: 'bara'}, {name: 'ons'}, 
								{name: 'ruba'}, {name: 'salim'}, {name: 'sofian'}, {name: 'mejri'}, 
								{name: 'znazen'}, {name: 'wajdii'}, {name: 'zied'}, {name: 'matt'}, 
								{name: 'yousef'}, {name: 'tam'}, {name: 'seif'}, {name: 'omar'}, {name: 'raghda'}];